version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    secrets:
      - master_key
    networks:
      - cybersec-net
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
    tty: true
    stdin_open: true
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password_manager
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cybersec-net
networks:
  cybersec-net:
    driver: bridge
secrets:
  master_key:
    file: ./docker/master_key.txt
volumes:
  db-data: